export const listTools = [
  {
    id: 1,
    gambar: "assets/tools/vscode.png",
    nama: "Visual Studio Code",
    ket: "Code Editor",
    dad: "100",
  },
  {
    id: 2,
    gambar: "assets/tools/reactjs.png",
    nama: "React JS",
    ket: "Framework",
    dad: "200",
  },
  {
    id: 3,
    gambar: "assets/tools/tailwind.png",
    nama: "Tailwind CSS",
    ket: "Framework",
    dad: "300",
  },
  {
    id: 4,
    gambar: "assets/tools/bootstrap.png",
    nama: "Bootstrap",
    ket: "Framework",
    dad: "400",
  },
  {
    id: 5,
    gambar: "assets/tools/js.png",
    nama: "JavaScript",
    ket: "Language",
    dad: "500",
  },
  {
    id: 6,
    gambar: "assets/tools/nodejs.png",
    nama: "Javascript Runtime",
    dad: "600",
  },
  {
    id: 7,
    gambar: "assets/tools/github.png",
    nama: "GitHub",
    ket: "Repository",
    dad: "700",
  },
  {
    id: 8,
    gambar: "assets/tools/canva.png",
    nama: "Canva",
    ket: "Design App",
    dad: "800",
  },
  {
    id: 9,
    gambar: "assets/tools/figma.png",
    nama: "Figma",
    ket: "Design App",
    dad: "900",
  },
  {
    id: 10,
    gambar: "assets/tools/kotlin.png",
    nama: "Kotlin",
    ket: "Language",
    dad: "1000",
  },
  {
    id: 11,
    gambar: "assets/tools/html.png",
    nama: "HTML",
    ket: "Language",
    dad: "1100",
  },
  {
    id: 12,
    gambar: "assets/tools/css.png",
    nama: "CSS",
    ket: "Language",
    dad: "1200",
  },
  {
    id: 13,
    gambar: "assets/tools/php.png",
    nama: "PHP",
    ket: "Language",
    dad: "1300",
  },
  {
    id: 14,
    gambar: "assets/tools/mysql.png",
    nama: "MySQL",
    ket: "Framework",
    dad: "1400",
  },
  {
    id: 15,
    gambar: "vite.svg",
    nama: "Java",
    ket: "Language",
    dad: "1500",
  },
  {
    id: 16,
    gambar: "vite.svg",
    nama: "Python",
    ket: "Language",
    dad: "1600",
  },
];

export const listProyek = [
  {
    id: 1,
    image: "assets/proyek/zencha.png",
    title: "ZenCha Shop ",
    subtitle: "Zencha Coffe using PHP and XAMPP...",
    fullDescription:"The Zencha Tea Website is a web-based application developed using PHP and MySQL. The system is designed to introduce Zencha tea products, provide product information, and support basic online ordering. Users can browse products and submit orders, while administrators can manage products, orders, and website content. The project aims to create a simple, user-friendly tea business website with efficient data management.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/vuongngan-se",
    dad: "100",
  },
  {
    id: 2,
    image: "assets/proyek/pomodoroweb.png",
    title: "Pomodoro Timer Website",
    subtitle: "The Pomodoro Timer is a...",
    fullDescription:"The Pomodoro Timer is a web-based application developed using HTML, CSS, and JavaScript with XAMPP (MySQL) for data storage. The system helps users manage their time effectively by applying the Pomodoro technique, which alternates focused work sessions and short breaks. Users can start, pause, and reset timers, and their session data can be stored for tracking productivity. The project aims to provide a simple, responsive, and user-friendly tool to improve concentration and time management.",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/vuongngan-se",
    dad: "200",
  },
  {
    id: 3,
    image: "assets/proyek/gymmanage.png",
    title: "Gym Management System",
    subtitle: "The Gym Management System is a...",
    fullDescription:"The Gym Management System is a Python-based desktop application with a graphical user interface and a relational database. The system helps manage gym members, membership packages, trainers, and attendance records. It supports member registration, package subscription, and daily check-in tracking. A dashboard module provides visual reports on membership statistics, attendance trends, and revenue. The system aims to improve management efficiency and reduce manual work in gym operations.",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/vuongngan-se",
    dad: "300",
  },
];
